more adaptations needed to boot vms and create images without direct root access
Will end in:

ValueError: Detected incompatible dependency guisetup.noop via [object] longsuffix='image1_vm2', shortname='' of [node] longprefix='025-net1.vm1.vm2.vm3', shortname='leaves.tutorial_get.implicit_both.vm1.virtio_rng.rng_random.qcow2.virtio_blk.smp2.virtio_net.CentOS.8.0.x86_64.net1.vm2.qcow2.virtio_blk.smp2.virtio_net.q35.Win10.x86_64.net1.vm3.qcow2.virtio_blk.smp2.virtio_net.Ubuntu.14.04.3-server.x86_64.net1'

Please include the traceback info and command line used on your bug report
Report bugs visiting https://github.com/avocado-framework/avocado/issues/new