modify root states only via the show state policy
The explicit root state get/set/unset operations are now dropped
as the root state is only truly applicable to some state backends
and had to be improvised via far-fetched associations for others.

This allows to drop additional complex cases of overwriting or the
lack of such (e.g. for vm boot) by only allowing root creation if
it didn't exist before and replacing any redundant recreaction with
an explicit root removal which is available only if the root existed
before the show states (or indirect state operation) invocation.

TODO: Integration tests raise extra design questions.
TODO: More adaptations are needed to boot vms and create images
without direct root access as current integration tests end in:

ValueError: Detected incompatible dependency guisetup.noop via [object] longsuffix='image1_vm2', shortname='' of [node] longprefix='025-net1.vm1.vm2.vm3', shortname='leaves.tutorial_get.implicit_both.vm1.virtio_rng.rng_random.qcow2.virtio_blk.smp2.virtio_net.CentOS.8.0.x86_64.net1.vm2.qcow2.virtio_blk.smp2.virtio_net.q35.Win10.x86_64.net1.vm3.qcow2.virtio_blk.smp2.virtio_net.Ubuntu.14.04.3-server.x86_64.net1'

which may now be fixed but with and extra diff but we have to make
sure.